-- SOLVAREN migration 0005 — Failure-reason dictionary seed.
--
-- GENERATED FILE — do not edit by hand. Regenerate with `pnpm db:generate-seed`.
-- Dictionary version: 2026.09.14

INSERT INTO failure_reason_map (provider_code, organization_id, reason, failure_class, operator_action, transient)
VALUES
  ('0', NULL, 'Processed successfully', 'UNKNOWN', 'No action required', false),
  ('00.002.1001', NULL, 'M-PESA is under maintenance', 'PROVIDER', 'Releases are paused automatically; retry after the maintenance window', true),
  ('1', NULL, 'Insufficient balance in the organization''s Utility account', 'FUNDING', 'Top up the B2C shortcode, or move funds from the Working (MMF) account to Utility on the M-PESA org portal — B2C debits Utility, not Working', true),
  ('100000000', NULL, 'M-PESA has cached the request and is waiting to resend it — the payment may still complete', 'AMBIGUOUS', 'Do not resend. Wait for the callback or run a status query on this OriginatorConversationID', true),
  ('100000001', NULL, 'M-PESA reports the system is overloaded', 'PROVIDER', 'The reconciliation sweep will re-check', true),
  ('100000002', NULL, 'M-PESA throttling error', 'PROVIDER', 'Throughput is throttled automatically; the sweep will re-check', true),
  ('100000004', NULL, 'M-PESA internal server error', 'PROVIDER', 'Reconcile before any retry', true),
  ('100000005', NULL, 'M-PESA rejected an input value as invalid', 'REQUEST', 'Check the instruction fields (amount, MSISDN, remarks); raise an engineering incident with the correlation id if they look correct', false),
  ('100000007', NULL, 'The M-PESA service status is abnormal', 'PROVIDER', 'Hold releases until Safaricom reports the service healthy; the reconciliation sweep will resolve in-flight payments', true),
  ('100000009', NULL, 'The API status is abnormal', 'PROVIDER', 'Hold releases until Safaricom reports the API healthy; the reconciliation sweep will resolve in-flight payments', true),
  ('100000010', NULL, 'Insufficient permissions on the M-PESA account', 'PERMISSION', 'Level 3: review the API operator roles on the org portal', false),
  ('100000011', NULL, 'M-PESA request rate limit exceeded', 'PROVIDER', 'Throughput is throttled automatically', true),
  ('11', NULL, 'The organization B2C account is not in an active state', 'PROVIDER', 'Contact Safaricom business support to reactivate the B2C shortcode; hold further releases until resolved', false),
  ('15', NULL, 'Duplicate request detected by M-PESA — this OriginatorConversationID was already seen', 'AMBIGUOUS', 'Do not resend. Run a status query on the original OriginatorConversationID to establish the true outcome', false),
  ('17', NULL, 'M-PESA internal failure', 'PROVIDER', 'Reconcile before any retry; escalate to Safaricom if it repeats', true),
  ('18', NULL, 'Initiator credential check failed (wrong password or an encryption/decryption problem)', 'CREDENTIAL', 'Level 3: regenerate the SecurityCredential against the current M-PESA public certificate and rotate the stored credential', false),
  ('19', NULL, 'Message sequencing failure at M-PESA', 'PROVIDER', 'Reconcile the transaction; escalate if it repeats', true),
  ('2', NULL, 'Amount is below the minimum permitted for this payment (M-PESA minimum is KES 10)', 'LIMIT', 'Correct the instruction amount and resubmit as a new instruction', false),
  ('20', NULL, 'Unresolved initiator — the API username was not found on the M-PESA portal', 'CREDENTIAL', 'Level 3: verify the InitiatorName matches an active API operator on the shortcode', false),
  ('2001', NULL, 'The initiator information is invalid (username, password, encryption or certificate)', 'CREDENTIAL', 'Level 3: test the Daraja connection, then rotate the initiator credential. Payments will keep failing identically until this is fixed', false),
  ('2006', NULL, 'Declined by an account rule — the B2C account is not active', 'PROVIDER', 'Contact Safaricom business support; hold releases until the account is active', false),
  ('2028', NULL, 'The paying shortcode is not permitted to perform B2C under its product assignment', 'PERMISSION', 'Level 3: confirm the shortcode is a Bulk Disbursement / one-account shortcode with B2C enabled', false),
  ('2040', NULL, 'The recipient is not a registered M-PESA customer', 'RECIPIENT', 'Verify the phone number on the recipient record. B2C CommandIDs only pay registered customers', false),
  ('21', NULL, 'The initiator is not permitted to perform this operation (missing the ORG B2C API Initiator role)', 'PERMISSION', 'Level 3: have the Business Administrator assign the "ORG B2C API Initiator" role to the API user', false),
  ('22', NULL, 'The initiator is not permitted to pay this receiver, or the initiator is not active', 'PERMISSION', 'Level 3: check the API operator is active and permitted for the receiving party', false),
  ('24', NULL, 'M-PESA rejected the request for missing mandatory fields', 'REQUEST', 'Raise an engineering incident — the submitted payload is incomplete', false),
  ('25', NULL, 'M-PESA could not convert one of the request parameters', 'REQUEST', 'Raise an engineering incident — a field is the wrong type', false),
  ('26', NULL, 'M-PESA is applying traffic blocking (system too busy)', 'PROVIDER', 'The reconciliation sweep will re-check; throughput is throttled automatically', true),
  ('29', NULL, 'M-PESA rejected the command as invalid', 'REQUEST', 'Raise an engineering incident — the CommandID is not valid for this shortcode', false),
  ('3', NULL, 'Amount exceeds the maximum permitted per transaction (M-PESA B2C maximum is KES 250,000)', 'LIMIT', 'Split the payment across multiple instructions within the per-transaction limit', false),
  ('4', NULL, 'Payment would exceed the recipient''s daily M-PESA transfer limit (KES 500,000)', 'LIMIT', 'Pay the balance on a later date, or ask the recipient to confirm their limit with Safaricom', true),
  ('400.002.02', NULL, 'Daraja rejected a field in the request as invalid', 'REQUEST', 'Raise an engineering incident with the correlation id', false),
  ('400.002.05', NULL, 'Daraja rejected the request payload as malformed', 'REQUEST', 'Raise an engineering incident with the correlation id', false),
  ('400.003.01', NULL, 'The Daraja access token was invalid or expired', 'CREDENTIAL', 'The token cache refreshes automatically; if it persists, Level 3 should re-test the Daraja connection', true),
  ('400.003.02', NULL, 'Daraja rejected the request as incomplete', 'REQUEST', 'Raise an engineering incident with the correlation id', false),
  ('401.001', NULL, 'The Daraja access token was rejected for this API product', 'CREDENTIAL', 'Level 3: confirm the Daraja app has the B2C product enabled, then re-test the connection', true),
  ('401.002.01', NULL, 'The Daraja access token was rejected', 'CREDENTIAL', 'Level 3: verify the consumer key and secret, then re-test the connection', true),
  ('404.001.03', NULL, 'The Daraja access token was rejected as invalid', 'CREDENTIAL', 'Level 3: verify the consumer key and secret, then re-test the connection', true),
  ('404.001.04', NULL, 'Daraja rejected the authentication header or HTTP method', 'REQUEST', 'Raise an engineering incident with the correlation id — all M-PESA calls are POST except token generation', false),
  ('404.003.01', NULL, 'Daraja reports the endpoint does not exist for this API product', 'REQUEST', 'Raise an engineering incident — the endpoint path or the app product assignment is wrong', false),
  ('405.001', NULL, 'Method not allowed — Daraja expected a different HTTP verb', 'REQUEST', 'Raise an engineering incident with the correlation id', false),
  ('500.001.1001', NULL, 'Daraja internal server error while handling the request', 'PROVIDER', 'Reconcile before any retry — the payment may still have been processed', true),
  ('500.002.1001', NULL, 'Duplicate OriginatorConversationID — Daraja has already seen this request identifier', 'AMBIGUOUS', 'Do not resend. Query the transaction status for the original identifier to establish whether money moved', false),
  ('500.003.02', NULL, 'Spike arrest violation — request rate exceeded the permitted burst', 'PROVIDER', 'Throughput is throttled automatically; the sweep will re-check', true),
  ('500.003.03', NULL, 'Quota violation — the request exceeded the permitted TPS', 'PROVIDER', 'Throughput is throttled automatically; the sweep will re-check', true),
  ('500.003.1001', NULL, 'Daraja internal server error', 'PROVIDER', 'Reconcile before any retry', true),
  ('8', NULL, 'Payment would exceed the recipient''s maximum M-PESA wallet balance (KES 500,000)', 'LIMIT', 'Ask the recipient to withdraw funds before the payment is retried', true),
  ('8006', NULL, 'The API security credential is locked', 'CREDENTIAL', 'Level 3: ask the Business Administrator to unlock the API user password on the M-PESA org portal, then rotate the credential', false),
  ('SFC_IC0003', NULL, 'The operator does not exist — the phone number is invalid or unassigned', 'RECIPIENT', 'Correct the recipient MSISDN on the master record and issue a new instruction', false),
  ('SLV_INTEGRATION_DISABLED', NULL, 'The Daraja integration was disabled before this instruction could be submitted', 'CREDENTIAL', 'Level 3: re-enable the integration in Settings → Daraja, then reissue the instruction', false),
  ('SLV_NO_CALLBACK', NULL, 'The request was accepted by M-PESA but no result callback has arrived', 'AMBIGUOUS', 'Reconciliation is querying the Transaction Status API. Do not resubmit until the outcome is known', false),
  ('SLV_QUEUE_TIMEOUT', NULL, 'M-PESA reported the request timed out while queued for processing', 'AMBIGUOUS', 'Reconciliation is querying the Transaction Status API. Do not resubmit until the outcome is known', false),
  ('SLV_RETRY_ISSUED', NULL, 'This transaction is the retry of an earlier failed instruction', 'UNKNOWN', 'See the original transaction for the underlying failure reason', false),
  ('SLV_SUBMIT_FAILED', NULL, 'SOLVAREN could not deliver the request to M-PESA', 'PROVIDER', 'The instruction was never accepted, so no money moved. It can be safely reissued once connectivity is restored', true),
  ('SLV_TIMEOUT', NULL, 'No result was received from M-PESA within the expected window', 'AMBIGUOUS', 'Reconciliation is querying the Transaction Status API. Do not resubmit until the outcome is known', false)
ON CONFLICT (organization_id, provider_code) DO UPDATE SET
  reason = EXCLUDED.reason,
  failure_class = EXCLUDED.failure_class,
  operator_action = EXCLUDED.operator_action,
  transient = EXCLUDED.transient;
