/**
 * Identifiers and references.
 *
 * Primary keys are UUIDv4 (generated by the application, never the database, so an
 * id exists before the row). Human-facing references are prefixed, time-sortable and
 * unambiguous in conversation: `SLV-2026-000184`, `APR-8821`, `BAK-2026-000184`.
 *
 * Randomness comes from the Web Crypto API (available in Node 18+, browsers and edge
 * runtimes alike) so the kernel stays platform-free: the browser bundle imports this
 * module for `formatCents` and must not drag `node:crypto` with it.
 */

export function newId(): string {
  return crypto.randomUUID();
}

/** Cryptographically random URL-safe token of `bytes` entropy. */
export function randomToken(bytes = 32): string {
  const buffer = new Uint8Array(bytes);
  crypto.getRandomValues(buffer);
  let binary = '';
  for (const b of buffer) binary += String.fromCharCode(b);
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

const PREFIXES = {
  batch: 'SLV',
  approval: 'APR',
  rejection: 'REJ',
  submission: 'SUB',
  hold: 'HLD',
  authorization: 'AUT',
  export: 'EXP',
  report: 'RPT',
  backup: 'BAK',
  reconciliation: 'REC',
  template: 'TPL',
  instruction: 'INS',
} as const;

export type ReferenceKind = keyof typeof PREFIXES;

/**
 * A short human reference with a per-process counter, e.g. `SLV-8821`.
 *
 * The counter is process-local by design: the *primary* identifier is always the UUID;
 * the reference exists so a human can say it over the phone. Collisions across processes
 * are impossible to confuse because the UUID is what every query uses.
 */
const counters = new Map<string, number>();
export function reference(kind: ReferenceKind): string {
  const next = (counters.get(kind) ?? 1_000 + Math.floor(Math.random() * 8_000)) + 1;
  counters.set(kind, next);
  return `${PREFIXES[kind]}-${next}`;
}

/** `cor_ABCDEFGHIJKLMNOPQRST` — correlation ids are recognisably ours and hard to guess. */
export function correlationId(): string {
  const buffer = new Uint8Array(10);
  crypto.getRandomValues(buffer);
  return `cor_${[...buffer].map((b) => b.toString(16).padStart(2, '0')).join('').toUpperCase()}`;
}

export const CORRELATION_PATTERN = /^cor_[A-Z0-9]{20}$/;

/** Daraja `OriginatorConversationID`: unique per submission attempt, opaque to recipients. */
export function originatorConversationId(shortCode: string, instructionId: string): string {
  return `SLV-${shortCode}-${instructionId.replace(/-/g, '').slice(0, 20)}-${Date.now().toString(36)}`;
}

export function isValidIdempotencyKey(key: string | undefined | null): boolean {
  if (typeof key !== 'string') return false;
  return key.length >= 16 && key.length <= 255;
}

/** Deterministic JSON for hashing: object keys sorted at every depth. */
export function stableStringify(value: unknown): string {
  return serialize(value);
}

function serialize(value: unknown): string {
  if (value === null || typeof value !== 'object') return JSON.stringify(value) ?? 'null';
  if (Array.isArray(value)) return `[${value.map(serialize).join(',')}]`;
  const entries = Object.entries(value as Record<string, unknown>)
    .filter(([, v]) => v !== undefined)
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  return `{${entries.map(([k, v]) => `${JSON.stringify(k)}:${serialize(v)}`).join(',')}}`;
}
